name: Mod release

permissions:
  contents: write

on:
  push:
    tags:
      - "v[0-9]+(\.[0-9]+)*([-\.]\S+)?"

  workflow_dispatch:

jobs:
  build:
    name: ""
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Prepare fabric jar
        working-directory: .
        run: |
          mkdir -p build/fabric
          cp ./common/* ./build/fabric
          cp -r ./fabric/* ./build/fabric
          cd build/fabric
          zip -r ${{ github.event.repository.name }}-fabric-$GITHUB_REF_NAME.jar .
          mv ${{ github.event.repository.name }}-fabric-$GITHUB_REF_NAME.jar ..

      - name: Prepare forge jar
        working-directory: .
        run: |
          mkdir -p build/forge
          cp ./common/* ./build/forge
          cp -r ./forge/* ./build/forge
          cd build/forge
          zip -r ${{ github.event.repository.name }}-forge-$GITHUB_REF_NAME.jar .
          mv ${{ github.event.repository.name }}-forge-$GITHUB_REF_NAME.jar ..

      - name: Upload fabric jar
        uses: actions/upload-artifact@v4.3.0
        with:
          name: ${{ github.event.repository.name }}-fabric-$GITHUB_REF_NAME
          path: build/${{ github.event.repository.name }}-fabric-$GITHUB_REF_NAME.jar
      - name: Upload forge jar
        uses: actions/upload-artifact@v4.3.0
        with:
          name: ${{ github.event.repository.name }}-forge-$GITHUB_REF_NAME
          path: build/${{ github.event.repository.name }}-forge-$GITHUB_REF_NAME.jar

      - run: |
          gh release create $GITHUB_REF_NAME build/*.jar
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
        shell: bash
        name: Creates a release in Github and uploads files from the build directory
